import { useEffect, useState } from 'react';
import Hero from './hero/Hero.jsx';
import Team from './sections/Team.jsx';
import Approach from './sections/Approach.jsx';
import EDA from './sections/EDA.jsx';
import Results from './sections/Results.jsx';
import Demo from './sections/Demo.jsx';
import { Report, Links } from './sections/ReportLinks.jsx';
import { loadIndex, loadVideo } from './data/load.js';
import './app.css';
import './sections/sections.css';

const NAV = [
  ['scene', 'Scene'],
  ['team', 'Team'],
  ['approach', 'Approach'],
  ['eda', 'EDA'],
  ['results', 'Results'],
  ['demo', 'Demo'],
  ['report', 'Report'],
  ['links', 'Links'],
];

function useActiveSection(ready) {
  const [active, setActive] = useState('scene');
  useEffect(() => {
    if (!ready) return undefined;
    const io = new IntersectionObserver(
      (entries) => {
        const vis = entries.filter((e) => e.isIntersecting).sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
        if (vis[0]) setActive(vis[0].target.id);
      },
      { rootMargin: '-30% 0px -60% 0px' },
    );
    NAV.forEach(([id]) => {
      const el = document.getElementById(id);
      if (el) io.observe(el);
    });
    return () => io.disconnect();
  }, [ready]);
  return active;
}

export default function App() {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    loadIndex()
      .then(async (idx) => ({ ...(await loadVideo(idx.videos[0].id)), pipelineCommit: idx.videos[0].pipeline_commit }))
      .then(setData)
      .catch((e) => setError(String(e)));
  }, []);
  const active = useActiveSection(!!data);

  return (
    <>
      <a className="skip" href="#scene">Skip to the scene</a>
      <header className="masthead">
        <div className="masthead-top">
          <a className="wordmark" href="#top">
            Zeroth Law Traffic
          </a>
          <span className="hand masthead-note">WIUT Hackathon 2026 · computer vision track</span>
        </div>
        <nav className="nav" aria-label="Sections">
          {NAV.map(([id, name]) => (
            <a key={id} href={`#${id}`} aria-current={active === id ? 'true' : undefined}>
              {name}
            </a>
          ))}
        </nav>
      </header>
      <main id="top">
        {error ? (
          <p className="load-state">
            Could not load the exported data ({error}). Run <code>scripts/export_web.py</code> first.
          </p>
        ) : data ? (
          <>
            <Hero data={data} />
            <Team />
            <Approach data={data} />
            <EDA data={data} />
            <Results data={data} />
            <Demo />
            <Report />
            <Links data={data} />
          </>
        ) : (
          <p className="load-state hand">unpacking the sketchbook…</p>
        )}
      </main>
      <footer className="footer">
        <p>
          Every number on this page is generated by <code>scripts/export_web.py</code> from our pipeline's output; the drawing is made in code.
          Sample footage provided by the hackathon organisers.
        </p>
      </footer>
    </>
  );
}
